import random 

# %% dict langs
dict_langs ={
'De':0,'Fr':1,'Es':2,'It':3,'La':4,'El':5,'Ru':6,'Iv':7,'Ar':8,'Hi':9,'Cn':10,
'de':0,'fr':1,'es':2,'it':3,'la':4,'el':5,'ru':6,'iv':7,'ar':8,'hi':9,'cn':10       
}


# %% dict allowed inputs
dict_allowed_inputs = {
'answer': ['a','b','c','d','A','B','C','D'],
'diff': ['E','M','H','e','m','h'],
'lang_select': ['De','Fr','Es','It','La','El','Ru','Iv','Ar','Hi','Cn','R','RR',
                'de','fr','es','it','la','el','ru','iv','ar','hi','cn','r','rr'],
'type_select': ['V','N','A','R','v','n','a','r']
}

# %% dict verbs
dict_verbs = {'to be' : ['zu sein', 'être', 'ser', 'essere', 'esse', 'να είναι', 'быть', 'להיות', 'أن تكون', 'होने के लिए', '成为'],
'to have' : ['haben', 'pour avoir', 'tener', 'avere', 'habere', 'να έχω', 'иметь', 'יש', 'امتلاك', 'रखने के लिए', '拥有'],
'to do' : ['machen', 'à faire', 'hacer', 'da fare', 'ad como', 'να κάνω', 'делать', 'לעשות', 'لكى يفعل', 'करने के लिए', '去做'],
'to say' : ['sagen', 'dire', 'decir', 'dire', 'Dicere', 'να πω', 'сказать', 'לומר', 'ليقول', 'कहने के लिए', '说'],
'to get' : ['bekommen', 'pour obtenir', 'Llegar', 'ottenere', 'ut', 'να πάρω', 'получить', 'להשיג', 'للحصول على', 'पाने के लिए', '要得到'],
'to make' : ['zu machen', 'faire', 'para hacer', 'produrre', 'facere', 'να κάνω', 'сделать', 'לעשות', 'ليصنع', 'बनाने के लिए', '制作'],
'to go' : ['gehen', 'aller', 'para llevar', 'andare', 'ire', 'να πάω', 'идти', 'ללכת', 'توجو', 'चल देना', '去'],
'to know' : ['wissen', 'à savoir', 'saber', 'sapere', 'scire', 'να γνωρίζεις', 'знать', 'לדעת', 'لمعرفة', 'जानने के लिए', '知道'],
'to take' : ['nehmen', 'prendre', 'tomar', 'prendere', 'capere', 'να παρεις', 'брать', 'לקחת', 'يأخذ', 'लेने के लिए', '拿'],
'to see' : ['um zu sehen', 'à voir', 'para ver', 'vedere', 'videre', 'για να δω', 'увидеть', 'לראות', 'لترى', 'देखने के लिए', '查看'],
'to come' : ['kommen', 'venir', 'venir', 'venire', 'venire', 'να έρθω', 'приходить', 'לבוא', 'ليأتي', 'आने के', '来'],
'to think' : ['denken', 'penser', 'pensar', 'pensare', 'cogitare', 'σκέφτομαι', 'думать', 'לחשוב', 'ليفكر', 'सोचना', '思考'],
'to look' : ['sehen', 'regarder', 'mirar', 'guardare', 'spectare', 'Για να κοιτάξω', 'смотреть', 'להסתכל', 'للنظر', 'देखने के लिए', '看'],
'to want' : ['wollen', 'vouloir', 'querer', 'volere', 'velle', 'να θέλω', 'хотеть', 'לרצות', 'لأريد', 'चाहने के लिए', '想要'],
'to give' : ['geben', 'pour donner', 'dar', 'dare', 'dare', 'το να δίνεις', 'дать', 'לתת', 'لكي أعطي', 'दे देना', '给'],
'to use' : ['benutzen', 'utiliser', 'usar', 'usare', 'uti', 'χρησιμοποιώ', 'использовать', 'להשתמש', 'ليستخدم', 'उपयोग करने के लिए', '使用'],
'to find' : ['finden', 'trouver', 'encontrar', 'trovare', 'invenire', 'να βρω', 'найти', 'למצוא', 'لايجاد', 'ढूँढ़ने के लिए', '找到'],
'to tell' : ['erzählen', 'dire', 'decir', 'dire', 'narrat', 'να πει', 'рассказать', 'לספר', 'يخبر', 'बताने के लिए', '告诉'],
'to ask' : ['Fragen', 'demander', 'preguntar', 'chiedere', 'rogare', 'να ρωτήσω', 'спросить', 'לשאול', 'يسأل', 'पूछना', '问'],
'to work' : ['arbeiten', 'travailler', 'trabajar', 'lavorare', 'laborare', 'για να δουλέψω', 'работать', 'לעבוד', 'للعمل', 'काम करने के लिए', '上班'],
'to seem' : ['scheinen', 'sembler', 'al parecer', 'sembrare', 'videri', 'να φαίνεται', 'казаться', 'להיראות', 'ليبدو', 'प्रतीत होना', '显得'],
'to feel' : ['fühlen', 'sentir', 'Sentir', 'sentire', 'sentire', 'νιώθω', 'чувствовать', 'להרגיש', 'تشعر', 'महसूस करने के लिए', '感觉'],
'to try' : ['versuchen', 'essayer', 'intentar', 'provare', 'ut tentaret', 'να δοκιμάσει', 'пытаться', 'לנסות', 'لكي يحاول', 'प्रयास करने के लिए', '尝试'],
'to leave' : ['verlassen', 'quitter', 'dejar', 'lasciare', 'ut relinquo', 'να φύγω', 'Покинуть', 'לעזוב', 'يغادر', 'छोड़ने के लिए', '离开'],
'to call' : ['anrufen', 'appeler', 'llamar', 'chiamare', 'vocare', 'για να καλέσετε', 'звонить', 'להתקשר', 'للإتصال', 'कॉल करने के लिए', '打电话'],
'to show' : ['zeigen', 'montrer', 'mostrar', 'mostrare', 'ostendere', 'να δείξω', 'показывать', 'להציג', 'ليعرض', 'दिखाने के लिए', '以显示'],
'to need' : ['brauchen', 'avoir besoin', 'necesitar', 'aver bisogno', 'egere', 'Να χρειάζεσαι', 'нуждаться', 'להצטרך', 'لكى يحتاج للحاجه', 'जरूरत को', '需要'],
'to become' : ['werden', 'devenir', 'convertirse', 'diventare', 'ut facti', 'να γίνω', 'стать', 'להפוך ל', 'لتصبح', 'बनना', '成为'],
'to include' : ['einschließen', 'inclure', 'para incluir', 'includere', 'ut comprehendo', 'να συμπεριλάβει', 'включать', 'לכלול', 'لكي يتضمن', 'शामिल करना', '包括'],
'to continue' : ['weitermachen', 'continuer', 'continuar', 'continuare', 'continere', 'να συνεχίσει', 'продолжить', 'להמשיך', 'لاستكمال', 'जारी रखने के लिए', '接着说'],
'to set' : ['zu setzen', 'mettre en place', 'para establecer', 'impostare', 'ponere', 'να ορίσει', 'установить', 'כדי להגדיר', 'لتعيين', 'स्थापित करना', '设置'],
'to start' : ['anfangen', 'commencer', 'para comenzar', 'iniziare', 'ut satus', 'να ξεκινήσω', 'начать', 'להתחיל', 'للبدأ', 'शुरू करना', '开始'],
'to help' : ['helfen', 'aider', 'ayudar', 'aiutare', 'adiuvare', 'να βοηθήσω', 'помочь', 'לעזור', 'للمساعدة', 'मदद करने', '帮助'],
'to talk' : ['sprechen', 'parler', 'hablar', 'parlare', 'dicere', 'να μιλήσω', 'поговорить', 'לדבר', 'لكي نتحدث', 'बातचीत करना', '说话'],
'to turn' : ['drehen', 'tourner', 'para girar', 'girare', 'ad conversus', 'Για να γυρίσω', 'превратить', 'לפנות', 'للإلتفاف', 'चालू करने के लिए', '转'],
'to live' : ['Leben', 'vivre', 'vivir', 'vivere', 'vivere', 'να ζεις', 'жить', 'לחיות', 'ليعيش', 'जीने के लिए', '为了生活'],
'to belong' : ['gehören', 'appartenir', 'pertenecer', 'appartenere', 'pertinent ad', 'να ανήκουν', 'принадлежать', 'להשתייך', 'للانتماء', 'सदस्य बनने के लिए', '属于'],
'to stand' : ['stehen', 'pour rester', 'para parar', 'Stare in piedi', 'stare', 'στέκομαι', 'стоять', 'לעמוד', 'للوقوف', 'सहन करना', '站立'],
'to pay' : ['bezahlen', 'payer', 'pagar', 'pagare', 'reddere', 'να πληρώσω', 'платить', 'לשלם', 'لدفع', 'भुगतान करने के लिए', '支付'],
'to contain' : ['enthalten', 'contenir', 'contener', 'contenere', 'ad continere', 'να περιέχει', 'содержать', 'להכיל', 'لاحتواء', 'शामिल करने के लिए', '包含装有'],
'to follow' : ['Folgen', 'suivre', 'seguir', 'da seguire', 'sequi', 'ακολουθώ', 'следить', 'לעקוב', 'للمتابعة', 'का अनुसरण', '跟随'],
'to happen' : ['passieren', 'se passer', 'suceder', 'accadere', 'fieri', 'να συμβεί', 'случаться', 'לקרות', 'يحدث', 'होना', '即将发生'],
'to occur' : ['passieren', 'arriver', 'que se produzca', 'verificare', 'fieri', 'να συμβεί', 'происходить', 'להתרחש', 'لتحدث', 'होने के लिये', '发生'],
'to present' : ['präsentieren', 'présenter', 'presentar', 'presentare', 'ut sisterent', 'να παρουσιάσει', 'представлять', 'להציג', 'للحضور', 'प्रस्तुत करना', '展示'],
'to require' : ['benötigen', 'requérir', 'requerir', 'richiedere', 'requirere', 'να απαιτήσει', 'требовать', 'לדרוש', 'يتطلب', 'आवश्यकता के लिए', '要求'],
'to produce' : ['produzieren', 'produire', 'para producir', 'produrre', 'ad producendum', 'για την παραγωγή', 'производить', 'כדי לייצר', 'لانتاج', 'उत्पादन करना', '生产'],
'to vary' : ['variieren', 'faire varier', 'variar', 'variare', 'ad variantur', 'να ποικίλλει', 'варьироваться', 'לשנות', 'تختلف', 'भिन्न करने के लिए', '改变'],
'to remain' : ['bleiben', 'rester', 'para permanecer', 'rimanere', 'manere', 'να παραμείνουν', 'оставаться', 'להישאר', 'للتذكير', 'बने रहना', '保留'],
'to cause' : ['verursachen', 'pour provoquer', 'causar', 'causare', 'ut faciam', 'για να προκαλεσει', 'вызывать', 'לגרום', 'لسبب', 'करवाना', '引起'],
'to bring' : ['bringen', 'apporter', 'traer', 'portare', 'ferre', 'να φέρει', 'принести', 'להביא', 'لجلب', 'लाने के लिए', '带来'],
'to hold' : ['halten', 'tenir', 'sostener', 'tenere', 'tenere', 'να κρατήσω', 'держать', 'להחזיק', 'ليمسك', 'पकड़ने के लिए', '保持'],
'to lead' : ['führen', 'mener', 'para liderar', 'guidare', 'ducere', 'να οδηγήσω', 'вести', 'להוביל', 'لقيادة', 'नेतृत्व करने के लिए', '领导'],
'to play' : ['spielen', 'jouer', 'jugar', 'giocare', 'ludere', 'να παίξουμε', 'играть', 'לשחק', 'للعب', 'खेलने के लिए', '玩'],
'to relate' : ['sich beziehen', 'pour raconter', 'para relacionar', 'mettere in relazione', 'ad', 'να συσχετίσει', 'чтобы связать', 'להתייחס', 'لربط', 'संबंधित करने के लिए', '关联'],
'to add' : ['hinzufügen', 'ajouter', 'Para agregar', 'aggiungere', 'addere', 'να προσθέσω', 'добавить', 'להוסיף', 'لإضافة', 'जोड़ने के लिए', '加上'],
'to allow' : ['erlauben', 'autoriser', 'permitir', 'permettere', 'licere', 'να επιτρέπεις', 'позволять', 'לאפשר', 'لكى يسمح', 'अनुमति देने के लिए', '允许'],
'to constitute' : ['zu konstituieren', 'constituer', 'Para constituir', 'costituire', 'ad constituere', 'για να αποτελέσω', 'составлять', 'להוות', 'تشريع', 'का गठन करने के लिए', '构成'],
'to involve' : ['involvieren', 'impliquer', 'involucrar', 'coinvolgere', 'involvere', 'για τη συμμετοχή', 'привлекать', 'לערב', 'لإشراك', 'शामिल होने के लिए', '参与'],
'to represent' : ['zu repräsentieren', 'représenter', 'representar', 'rappresentare', 'repraesentare', 'Για να εκπροσωπώ', 'представлять', 'לייצג', 'لتمثيل', 'प्रतिनिधित्व करना', '代表'],
'to express' : ['ausdrücken', 'exprimer', 'para expresar', 'esprimere', 'exprimere', 'να εκφράσουν', 'выражать', 'להביע', 'للتعبير', 'व्यक्त करना', '表达'],
'to suggest' : ['vorschlagen', 'suggérer', 'sugerir', 'suggerire', 'ad suadeant', 'να προτείνουν', 'предлагать', 'להציע', 'ليقترح', 'करने के लिए सुझाव', '建议'],
'to apply' : ['bewerben', 'postuler', 'Aplicar', 'applicare', 'ponere', 'να εφαρμόσει', 'применять', 'ליישם', 'للتقديم', 'लागू करने के लिए', '申请'],
'to measure' : ['messen', 'mesurer', 'para medir', 'misurare', 'ut metiretur', 'να μετρήσετε', 'измерять', 'למדוד', 'لقياس', 'मापने के लिए', '测量'],
'to affect' : ['beeinflussen', 'Affecter', 'afectar', 'influenzare', 'et afficit', 'να επηρεάσουν', 'влиять', 'להשפיע', 'ليؤثر', 'प्रभावित करने के लिए', '影响'],
'to influence' : ['beeinflussen', 'influencer', 'influenciar', 'influenzare', 'ad influentiam', 'να επηρεάζει', 'влиять', 'להשפיע', 'ليؤثر', 'प्रभावित करने के लिए', '去影响'],
'to direct' : ['Regie führen', 'à diriger', 'dirigir', 'dirigere', 'ut recta', 'να κατευθύνω', 'направлять', 'לכוון', 'لتوجيه', 'निर्देशित करना', '直接'],
'to form' : ['Formen', 'former', 'formar', 'per formare', 'formare', 'σχηματίζω', 'для формирования', 'כדי ליצור', 'لتشكيل', 'बनाने के लिए', '来形成'],
'to function' : ['Funktionieren', 'Pour fonctionner', 'funcionar', 'funzionare', 'munus', 'για να λειτουργήσει', 'функционировать', 'לתפקד', 'للعمل', 'कार्य करना', '功能'],
'to operate' : ['zu bedienen', 'opérer', 'para operar', 'operare', 'ad agunt', 'να λειτουργεί', 'работать', 'להפעיל', 'ليشغل', 'संचालित करने के लिए', '操作'],
'to maintain' : ['aufrecht erhalten', 'Maintenir', 'mantener', 'mantenere', 'ponere', 'διατηρω', 'поддерживать', 'לשמר', 'للحفاظ', 'बनाए रखने के लिए', '维护'],
'to control' : ['kontrollieren', 'contrôller', 'al control', 'controllare', 'ad imperium', 'ελέγχω', 'контролировать', 'לשלוט', 'ليتحكم', 'नियंत्रण करने के लिए', '控制'],
'to depend' : ['abhängen', 'dépendre', 'depender', 'dipendere', 'dependet', 'να εξαρτάται', 'зависеть', 'להסתמך', 'لكي تعتمد', 'निर्भर करने के लिए', '依靠'],
'to derive' : ['ableiten', 'dériver', 'para derivar', 'derivare', 'DESINO', 'να αντλήσει', 'вывести', 'לנהוג', 'ليشتق', 'प्राप्त करने के लिए', '推导'],
'to benefit' : ['zu profitieren', 'profiter', 'beneficiarse', 'a vantaggio', 'ut prodesse', 'προς όφελός', 'Чтобы получить пользу', 'להרוויח', 'لفائدة', 'लाभ के लिए', '受益'],
'to suffer' : ['leiden', 'souffrir', 'sufrir', 'soffrire', 'pati', 'να υποφέρουν', 'страдать', 'לסבול', 'يعاني', 'भुगतना', '受苦'],
'to participate' : ['teilnehmen', 'participer', 'para participar', 'partecipare', 'participare', 'να συμμετάσχουν', 'участвовать', 'להשתתף', 'كي يشارك', 'भाग लेने के लिए', '参加'],
'to contribute' : ['beitragen', 'contribuer', 'contribuir', 'contribuire', 'contribuere', 'να συνεισφέρω', 'способствовать', 'לתרום', 'للمساهمة', 'योगदान करना', '做出贡献'],
'to result' : ['resultieren', 'résulter', 'para ser resultado', 'risultare', 'ut', 'στο αποτέλεσμα', 'в результате', 'לתוצאות', 'للنتيجة', 'नतीजे पर', '导致'],
'to generate' : ['generieren', 'générer', 'para generar', 'generare', 'generate', 'να δημιουργήσει', 'генерировать', 'לייצר', 'لتوليد', 'पैदा करना', '生成'],
'to motivate' : ['motivieren', 'motiver', 'motivar', 'motivare', 'ad motivate', 'να παρακινήσει', 'мотивировать', 'להניע', 'لتحفيز', 'प्रेरणा देना', '激励'],
'to encourage' : ['ermutigen', 'encourager', 'para fomentar', 'incoraggiare', 'ad robora', 'να ενθαρρύνει', 'поощрять', 'כדי לעודד', 'لتشجيع', 'प्रोत्साहित करना', '鼓励'],
'to facilitate' : ['zu erleichtern', 'faciliter', 'facilitar', 'per facilitare', 'ad facilitate', 'να διευκολύνει', 'облегчить', 'להקל', 'لتسهيل', 'आसान बनाना', '促进'],
'to promote' : ['befördern', 'promouvoir', 'promover', 'promuovere', 'promote', 'Για να προωθησω', 'продвигать', 'לקדם', 'انا ارقي', 'बढ़ावा देना', '推广'],
'to support' : ['zu unterstützen', 'soutenir', 'apoyar', 'supportare', 'ad firmamentum', 'για να στηρίξει', 'поддерживать', 'לתמוך', 'من أجل دعم', 'समर्थन के लिए', '支持'],
'to enhance' : ['zu verbessern', 'améliorer', 'para mejorar', 'per migliorare', 'ad augendae', 'για βελτίωση', 'для улучшения', 'כדי לשפר את', 'لتعزيز', 'बढ़ाने के लिए', '加强'],
'to defend' : ['zu verteidigen', 'défendre', 'defender', 'per difendere', 'defendere', 'για να υπερασπιστώ', 'защищать', 'להגן', 'للدفاع', 'बचाव करने के लिए', '保卫'],
'to challenge' : ['herausfordern', 'mettre au défi', 'desafiar', 'sfidare', 'ut challenge', 'για να προκαλέσει', 'соревноваться', 'לאתגר', 'تحدي', 'चुनौती देने के लिए', '去挑战'],
'to prevent' : ['verhindern', 'pour prévenir', 'para prevenir', 'impedire', 'prohibere', 'να αποτρέψω', 'предотвращать', 'למנוע', 'كى تمنع', 'रोकने के लिए', '阻止'],
'to restrict' : ['einschränken', 'restreindre', 'restringir', 'restringere', 'ad restringere', 'να περιορίσει', 'ограничивать', 'להגביל', 'لتقييد', 'प्रतिबंधित करना', '限制'],
'to ban' : ['verbannen', 'exclure', 'para prohibir', 'bandire', 'movebo', 'να απαγορεύσει', 'запрещать', 'לאסור', 'لحظر', 'प्रतिबंध लगाने के लिए', '取缔'],
'to prohibit' : ['verbieten', 'interdire', 'Prohibir', 'proibire', 'prohibeo', 'απαγορεύω', 'запрещать', 'לאסור', 'لحظر', 'निषेध करना', '禁止'],
'to deny' : ['bestreiten', 'nier', 'denegar', 'negare', 'negare', 'να αρνηθώ', 'отрицать', 'להכחיש', 'للرفض', 'इनकार करना', '否认'],
'to oppose' : ['ablehnen', 's\'opposer', 'oponerse', 'opporre', 'ad resistere', 'για να αντιταχθώ', 'противостоять', 'להתנגד', 'لمعارضة', 'विरोध करना', '反对'],
'to resist' : ['widerstehen', 'à résister', 'resistir', 'resistere', 'resisto', 'αντιστέκομαι', 'сопротивляться', 'להתנגד', 'كي أقاوم', 'प्रतिरोध करने के लिए', '抵抗'],
'to block' : ['blockieren', 'bloquer', 'bloquear', 'bloccare', 'ut angustos', 'να εμποδίσει', 'блокировать', 'לחסום', 'ليحجب', 'रुकावट के लिए', '阻止'],
'to halt' : ['anhalten', 'faire halte', 'a detenerse', 'fermare', 'ut', 'να σταματήσει', 'остановить', 'לעצור', 'لتوقف', 'पड़ाव के लिए', '停止'],
'to stop' : ['stoppen', 'arrêter', 'para detener', 'fermare', 'prohibere', 'να σταματήσει', 'прекратить', 'לעצור', 'للتوقف', 'रोकने के लिए', '停止'],
'to obstruct' : ['zu behindern', 'obstruer', 'para obstruir', 'ostruire', 'impedimentum', 'να εμποδίσω', 'чтобы препятствовать', 'להכשיל', 'لعرقلة', 'बाधा डालना', '阻碍'],
'to interrupt' : ['unterbrechen', 'interrompre', 'para interrumpir', 'interrompere', 'interrupto', 'Για να διακόψω', 'прервать', 'להפריע', 'ليقطع', 'बाधित करने के लिए', '打断'],
'to disrupt' : ['zu stören', 'pour perturber', 'para interrumpir', 'interrompere', 'ut perturbare', 'διακόπτω', 'чтобы нарушить', 'להפריע', 'لتعطيل', 'बाधित करने के लिए', '破坏']
}

# %% dict nouns
dict_nouns = {'the time' : ['die Zeit', 'le temps', 'el tiempo', 'il tempo', 'tempus', 'Η ωρα', 'время', 'הזמן', 'الوقت', 'समय', '时间'],
'the person' : ['die Person', 'la personne', 'la persona', 'la persona', 'personam', 'το πρόσωπο', 'человек', 'האדם', 'الشخص', 'व्यक्ति', '此人'],
'the year' : ['das Jahr', 'l\'année', 'el año', 'l\'anno', 'anno', 'το έτος', 'год', 'השנה', 'السنة', 'वर्ष', '那一年'],
'the way' : ['der Weg', 'le chemin', 'el camino', 'la via', 'via', 'ο ΤΡΟΠΟΣ', 'путь', 'הדרך', 'الطريقة', 'रास्ता', '方式'],
'the day' : ['der Tag', 'le jour', 'El dia', 'il giorno', 'dies', 'η μέρα', 'день', 'היום', 'اليوم', 'दिन', '那天'],
'the thing' : ['die Sache', 'la chose', 'la cosa', 'la cosa', 'rem', 'το πράγμα', 'вещь', 'הדבר', 'الشيء', 'बात', '事情'],
'the man' : ['der Mann', 'l\'homme', 'el hombre', 'l\'uomo', 'vir', 'ο άντρας', 'тот человек', 'האיש', 'الرجل', 'मनुष्य', '男人'],
'the government' : ['die Regierung', 'le gouvernement', 'el Gobierno', 'il governo', 'imperium', 'η κυβέρνηση', 'правительство', 'הממשלה', 'الحكومة', 'सरकार', '政府'],
'the company' : ['das Unternehmen', 'l\'entreprise', 'la compañia', 'l\'azienda', 'ad comitatu', 'η εταιρία', 'компания', 'החברה', 'الشركة', 'कंपनी', '公司'],
'the hand' : ['die Hand', 'la main', 'la mano', 'la mano', 'manus', 'το χέρι', 'рука', 'היד', 'اليد', 'हाथ', '手'],
'the part' : ['Das Teil', 'la partie', 'la parte', 'la parte', 'ex parte', 'το μέρος', 'часть', 'החלק', 'الجزء', 'भाग', '那个部分'],
'the place' : ['der Platz', 'le lieu', 'el lugar', 'il luogo', 'Locus', 'το μέρος', 'место', 'המקום', 'المكان', 'स्थान', '这个地方'],
'the group' : ['die Gruppe', 'le groupe', 'el grupo', 'il gruppo', 'coetus', 'η ομάδα', 'группа', 'הקבוצה', 'المجموعة', 'समूह', '群组'],
'the case' : ['der Fall', 'l\'affaire', 'el caso', 'il caso', 'causam', 'η υπόθεση', 'дело', 'המקרה', 'القضية', 'मुकदमा', '案子'],
'the week' : ['die Woche', 'la semaine', 'la semana', 'la settimana', 'in hebdomada', 'η εβδομάδα', 'неделя', 'השבוע', 'الإسبوع', 'सप्ताह', '星期'],
'the point' : ['Der Punkt', 'le point', 'el punto', 'il punto', 'punctum', 'το σημείο', 'точка', 'הנקודה', 'النقطة', 'बिंदु', '重点'],
'the home' : ['das Zuhause', 'la maison', 'el hogar', 'la casa', 'in domum suam', 'το σπίτι', 'дом', 'הבית', 'البيت', 'घर', '家'],
'the eye' : ['das Auge', 'l\'oeil', 'el ojo', 'l\'occhio', 'oculus', 'το μάτι', 'глаз', 'העין', 'العين', 'आँख', '眼'],
'the child' : ['das Kind', 'l\'enfant', 'el niño', 'il bambino', 'puer', 'το παιδί', 'ребенок', 'הילד', 'الطفل', 'बच्चा', '孩子'],
'the world' : ['die Welt', 'le monde', 'el mundo', 'il mondo', 'mundus', 'ο κόσμος', 'мир', 'העולם', 'العالم', 'दुनिया', '世界'],
'the school' : ['die Schule', 'l\'école', 'la escuela', 'la scuola', 'in schola', 'το σχολείο', 'школа', 'בית הספר', 'المدرسة', 'स्कूल', '学校'],
'the state' : ['der Staat', 'l\'état', 'el estado', 'lo stato', 'statum', 'το κράτος', 'штат', 'המדינה', 'الولاية', 'राज्य', '国家'],
'the family' : ['die Familie', 'la famille', 'la familia', 'la famiglia', 'genus', 'η οικογένεια', 'семья', 'המשפחה', 'العائلة', 'परिवार', '家庭'],
'the student' : ['der Student', 'l\'étudiant', 'el estudiante', 'lo studente', 'studiosum', 'ο μαθητής', 'студент', 'הסטודנט', 'الطالب', 'छात्र', '学生'],
'the friend' : ['der Freund', 'l\'ami', 'el amigo', 'l\'amico', 'amicum', 'ο φίλος', 'друг', 'החבר', 'الصديق', 'दोस्त', '朋友'],
'the life' : ['das Leben', 'la vie', 'la vida', 'la vita', 'vita', 'η ζωή', 'жизнь', 'החיים', 'الحياة', 'जीवन', '人生'],
'the area' : ['das Gebiet', 'la zone', 'la zona', 'l\'area', 'aream', 'η περιοχή', 'область', 'האזור', 'المنطقة', 'क्षेत्र', '该区域'],
'the country' : ['das Land', 'le pays', 'el país', 'Paese', 'patriam', 'η χώρα', 'страна', 'המדינה', 'البلد', 'देश', '这个国家'],
'the month' : ['der Monat', 'le mois', 'el mes', 'il mese', 'in mense', 'ο μήνας', 'месяц', 'החודש', 'الشهر', 'महीना', '这个月'],
'the work' : ['die Arbeit', 'l\'oeuvre', 'la obra', 'il lavoro', 'opus', 'η δουλειά', 'работа', 'העבודה', 'العمل', 'काम', '工作'],
'the system' : ['das System', 'le système', 'el sistema', 'il sistema', 'et ratio', 'το σύστημα', 'система', 'המערכת', 'النظام', 'प्रणाली', '系统'],
'the member' : ['das Mitglied', 'le membre', 'el miembro', 'il membro', 'in membrum', 'το μέλος', 'член', 'החבר', 'عضو', 'सदस्य', '成员'],
'the money' : ['das Geld', 'l\'argent', 'el dinero', 'i soldi', 'pecuniam', 'τα χρήματα', 'деньги', 'הכסף', 'المال', 'पैसा', '钱'],
'the problem' : ['das Problem', 'le problème', 'el problema', 'il problema', 'consultatio', 'το πρόβλημα', 'эта проблема', 'הבעיה', 'المشكلة', 'समस्या', '问题'],
'the fact' : ['die Tatsache', 'le fait', 'el hecho', 'il fatto', 'quod', 'Το γεγονός', 'факт', 'העובדה', 'الحقيقة', 'तथ्य', '事实'],
'the body' : ['der Körper', 'le corps', 'el cuerpo', 'il corpo', 'corpus', 'το σώμα', 'тело', 'הגוף', 'الجسم', 'शरीर', '身体'],
'the night' : ['die Nacht', 'la nuit', 'la noche', 'la notte', 'nox', 'η νύχτα', 'ночь', 'הלילה', 'الليل', 'रात', '夜晚'],
'the water' : ['das Wasser', 'l\'eau', 'el agua', 'l\'acqua', 'aqua', 'το νερό', 'вода', 'המים', 'الماء', 'पानी', '水'],
'the mother' : ['die Mutter', 'la mère', 'La madre', 'la madre', 'mater', 'η μητέρα', 'мать', 'האם', 'الأم', 'माता', '母亲'],
'the father' : ['der Vater', 'le père', 'el padre', 'il padre', 'pater', 'ο πατέρας', 'отец', 'האבא', 'الأب', 'पिता', '父亲'],
'the community' : ['die Gemeinde', 'la communauté', 'la comunidad', 'la comunità', 'in civitatem', 'η κοινότητα', 'сообщество', 'הקהילה', 'المجتمع', 'समुदाय', '社区'],
'the house' : ['das Haus', 'la maison', 'la casa', 'la casa', 'domus', 'το σπίτι', 'дом', 'הבית', 'المنزل', 'घर', '房子'],
'the number' : ['die Nummer', 'le nombre', 'el número', 'il numero', 'numerus', 'ο αριθμός', 'число', 'המספר', 'الرقم', 'रेखावृत्त', '号码'],
'the hour' : ['die Stunde', 'l\'heure', 'la hora', 'l\'ora', 'horam', 'η ώρα', 'час', 'השעה', 'ساعة', 'घंटा', '小时'],
'the city' : ['die Stadt', 'la ville', 'la ciudad', 'la città', 'urbs', 'η πόλη', 'город', 'העיר', 'المدينة', 'शहर', '城市'],
'the public' : ['die Öffentlichkeit', 'le public', 'el público', 'il pubblico', 'civium', 'το κοινό', 'публика', 'הציבור', 'الجمهور', 'जनता', '公众'],
'the president' : ['der Präsident', 'Le président', 'el presidente', 'il presidente', 'praeses', 'Ο Πρόεδρος', 'президент', 'הנשיא', 'الرئيس', 'अध्यक्ष', '总统'],
'the name' : ['der Name', 'le nom', 'el nombre', 'il nome', 'nomine', 'το όνομα', 'название', 'השם', 'الاسم', 'नाम', '名字'],
'the car' : ['das Auto', 'la voiture', 'el coche', 'l\'auto', 'currus', 'το αυτοκίνητο', 'машина', 'המכונית', 'السيارة', 'कार', '车'],
'the door' : ['die Tür', 'la porte', 'la puerta', 'la porta', 'ianua', 'η ΠΟΡΤΑ', 'дверь', 'הדלת', 'الباب', 'दरवाजा', '门'],
'the word' : ['das Wort', 'le mot', 'la palabra', 'la parola', 'verbum', 'η λέξη', 'слово', 'המילה', 'الكلمة', 'शब्द', '这个单词'],
'the service' : ['der Service', 'le service', 'el servicio', 'il servizio', 'in ministerium', 'η υπηρεσία', 'обслуживание', 'השירות', 'الخدمة', 'सेवा', '服务'],
'the health' : ['die Gesundheit', 'la santé', 'la salud', 'la salute', 'salutem', 'η υγεία', 'Здоровье', 'הבריאות', 'الصحة', 'तबीयत', '健康'],
'the law' : ['das Gesetz', 'la loi', 'la Ley', 'la legge', 'lex', 'ο νόμος', 'закон', 'החוק', 'القانون', 'कानून', '法律'],
'the job' : ['die Arbeit', 'le travail', 'el trabajo', 'il lavoro', 'officium', 'η εργασία', 'работа', 'העבודה', 'العمل', 'काम', '工作'],
'the food' : ['das Essen', 'la nourriture', 'los alimentos', 'il cibo', 'cibo', 'το φαγητό', 'еда', 'האוכל', 'الطعام', 'भोजन', '食物'],
'the oil' : ['das Öl', 'l\'huile', 'el aceite', 'l\'olio', 'et oleum', 'το λάδι', 'масло', 'השמן', 'الزيت', 'तैल', '油'],
'the form' : ['die Form', 'la forme', 'la forma', 'il modulo', 'forma', 'η μορφή', 'форма', 'הצורה', 'الاستمارة', 'फार्म', '表格'],
'the power' : ['die Macht', 'la puissance', 'el poder', 'il potere', 'in virtute', 'η εξουσία', 'сила', 'הכח', 'القوة', 'शक्ति', '动力'],
'the education' : ['die Bildung', 'l\'éducation', 'la educación', 'l\'educazione', 'in educatione', 'η εκπαίδευση', 'образование', 'החינוך', 'التعليم', 'शिक्षा', '教育'],
'the leader' : ['der Leiter', 'le meneur', 'el líder', 'il capo', 'dux', 'ο ηγέτης', 'лидер', 'המנהיג', 'القائد', 'नेता', '领导人'],
'the information' : ['die Information', 'l\'information', 'la información', 'l\'informazione', 'indicium', 'η πληροφορία', 'информация', 'המידע', 'المعلومات', 'सूचना', '信息'],
'the land' : ['das Land', 'la terre', 'la tierra', 'la terra', 'in terra', 'η γη', 'земля', 'הארץ', 'الأرض', 'भूमि', '那片土地'],
'the story' : ['die Geschichte', 'l\'histoire', 'la historia', 'la storia', 'in fabula', 'η ιστορία', 'история', 'הסיפור', 'القصة', 'कहानी', '故事'],
'the lot' : ['das Ganze', 'le terrain', 'la parcela', 'il lotto', 'sortem', 'παρτίδα', 'земельный участок', 'המגרש', 'الأكثر', 'बहुत ज्यादा', '很多'],
'the business' : ['das Geschäft', 'les affaires', 'el negocio', 'il business', 'negotium', 'η επιχείρηση', 'бизнес', 'העסק', 'العمل', 'व्यवसाय जिस', '这生意'],
'the issue' : ['Das Thema', 'le problème', 'la cuestión', 'il problema', 'exitus', 'το θέμα', 'проблема', 'הנושא', 'المشكلة', 'समस्या', '问题'],
'the process' : ['der Prozess', 'le processus', 'el proceso', 'il processo', 'processus', 'η διαδικασία', 'процесс', 'התהליך', 'العملية', 'प्रक्रिया', '该过程'],
'the policy' : ['die Richtlinie', 'la politique', 'La política', 'la politica', 'consilium', 'η πολιτική', 'политика', 'המדיניות', 'السياسة', 'नीति', '政策'],
'the game' : ['das Spiel', 'le jeu', 'el juego', 'il gioco', 'ludus', 'το παιχνίδι', 'игра', 'המשחק', 'اللعبة', 'खेल', '游戏'],
'the program' : ['das Programm', 'le programme', 'el programa', 'il programma', 'progressio', 'το πρόγραμμα', 'программа', 'התכנית', 'البرنامج', 'कार्यक्रम', '该程序'],
'the line' : ['die Linie', 'la ligne', 'la línea', 'la linea', 'linea', 'η γραμμή', 'линия', 'השורה', 'الخط', 'रेखा', '线'],
'the market' : ['der Markt', 'le marché', 'El mercado', 'il mercato', 'foro', 'η αγορά', 'магазин', 'השוק', 'السوق', 'बाजार', '市场'],
'the mind' : ['der Verstand', 'l\'esprit', 'la mente', 'la mente', 'animus', 'το μυαλό', 'разум', 'המחשבה', 'العقل', 'मन', '思想'],
'the war' : ['der Krieg', 'la guerre', 'la guerra', 'la guerra', 'bellum', 'ο πόλεμος', 'война', 'המלחמה', 'الحرب', 'युद्ध', '战争'],
'the side' : ['die Seite', 'le côté', 'el lado', 'il lato', 'latus', 'η πλευρά', 'сторона', 'הצד', 'الجانب', 'पक्ष', '旁边'],
'the art' : ['die Kunst', 'L\'art', 'el arte', 'l\'arte', 'arte', 'η τέχνη', 'искусство', 'האומנות', 'الفن', 'कला', '艺术'],
'the book' : ['das Buch', 'le livre', 'el libro', 'il libro', 'Liber', 'το βιβλίο', 'книга', 'הספר', 'الكتاب', 'पुस्तक', '这本书'],
'the science' : ['die Wissenschaft', 'la science', 'la ciencia', 'la scienza', 'scientia', 'η επιστήμη', 'наука', 'המדע', 'العلم', 'विज्ञान', '科学'],
'the order' : ['die Bestellung', 'l\'ordre', 'el orden', 'l\'ordine', 'ordinem', 'η σειρά', 'приказ', 'הסדר', 'الأمر - الطلب', 'आदेश', '命令'],
'the society' : ['die Gesellschaft', 'la société', 'la sociedad', 'la società', 'Societas', 'η κοινωνία', 'Общество', 'החברה', 'المجتمع', 'समाज', '社会'],
'the building' : ['Gebäude', 'le bâtiment', 'el edificio', 'l\'edificio', 'ad aedificationem', 'Το κτίριο', 'здание', 'הבניין', 'المبنى', 'ईमारत', '建筑物'],
'the security' : ['die Sicherheit', 'La sécurité', 'la seguridad', 'la sicurezza', 'securitas', 'Η ασφάλεια', 'охрана', 'הביטחון', 'الامن', 'सुरक्षा', '安全'],
'the freedom' : ['die Freiheit', 'la liberté', 'la libertad', 'la libertà', 'libertatem', 'ελευθερία', 'Свобода', 'החופש', 'الحرية', 'स्वतंत्रता', '自由'],
'the democracy' : ['die Demokratie', 'la démocratie', 'la democracia', 'la democrazia', 'Democracy', 'η δημοκρατία', 'демократия', 'הדמוקרטיה', 'الديمقراطية', 'लोकतंत्र', '民主'],
'the justice' : ['die Gerechtigkeit', 'la justice', 'la justicia', 'la giustizia', 'ad iustitiam', 'η δικαιοσύνη', 'Справедливость', 'הצדק', 'العدالة', 'न्यायाधीश', '正义'],
'the equality' : ['die Gleichheit', 'l\'égalité', 'la igualdad', 'l\'uguaglianza', 'aequalitatem', 'η ισότητα', 'равенство', 'השוויון', 'المساواة', 'समानता', '平等'],
'the rights' : ['die Rechte', 'les droits', 'los derechos', 'i diritti', 'IURIBUS', 'τα δικαιώματα', 'права', 'הזכויות', 'الحقوق', 'अधिकार', '权利'],
'the respect' : ['der Respekt', 'le respect', 'el respeto', 'il rispetto', 'respectu', 'ο σεβασμός', 'уважение', 'הכבוד', 'الاحترام', 'सम्मान', '尊重'],
'the honor' : ['die Ehre', 'l\'honneur', 'el honor', 'l\'onore', 'honor', 'Η τιμή', 'честь', 'הכבוד', 'الفخر', 'आदर', '荣誉'],
'the dignity' : ['die Würde', 'la dignité', 'la dignidad', 'la dignità', 'dignitas', 'η αξιοπρέπεια', 'достоинство', 'הכבוד', 'الكرامة', 'गरिमा', '尊严'],
'the responsibility' : ['die Verantwortung', 'la responsabilité', 'la responsabilidad', 'la responsabilità', 'responsibility', 'η ευθύνη', 'ответственность', 'האחריות', 'المسؤولية', 'जिम्मेदारी', '责任'],
'the accountability' : ['die Rechenschaftspflicht', 'la responsabilité', 'la responsabilidad', 'la responsabilità', 'ad accountability', 'η λογοδοσία', 'подотчетность', 'האחריות', 'المساءلة', 'जवाबदेही', '问责制'],
'the trust' : ['das Vertrauen', 'la confiance', 'la confianza', 'la fiducia', 'fiducia', 'η εμπιστοσύνη', 'доверие', 'האמון', 'الثقة', 'भरोसा', '信任'],
'the transparency' : ['die Transparenz', 'la transparence', 'la transparencia', 'la trasparenza', 'ad diaphanum', 'η διαφάνεια', 'прозрачность', 'השקיפות', 'الشفافية', 'पारदर्शिता', '透明度'],
'the integrity' : ['die Integrität', 'l\'intégrité', 'la integridad', 'l\'integrità', 'integritas', 'η ακεραιότητα', 'целостность', 'היושרה', 'سلامة', 'निष्ठा', '完整性'],
'the fairness' : ['die Fairness', 'L\'équité', 'la justicia', 'l\'equità', 'iustitia', 'η δικαιοσύνη', 'Справедливость', 'ההגינות', 'الإنصاف', 'निष्पक्षता', '公平'],
'the unity' : ['die Einheit', 'l\'unité', 'la unidad', 'l\'unità', 'unitas', 'η ενότητα', 'единство', 'האחדות', 'الوحدة', 'एकता', '团结'],
'the tolerance' : ['Die Toleranz', 'la tolérance', 'la tolerancia', 'la tolleranza', 'et tolerantia', 'η ανοχή', 'терпимость', 'הסובלנות', 'التسامح', 'सहिष्णुता', '公差'],
'the peace' : ['der Frieden', 'la paix', 'la paz', 'la pace', 'Pax', 'η ειρήνη', 'мир', 'השלום', 'السلام', 'शांति', '和平']
}

# %% dict adjs
dict_adjs = {'it is good' : ['es ist gut', 'c\'est bon', 'es bueno', 'è buono', 'bonum est', 'είναι καλό', 'это хорошо', 'זה טוב', 'انه جيد', 'अछा है', '这很好'],
'it is new' : ['es ist neu', 'c\'est nouveau', 'es nuevo', 'è nuovo', 'novi', 'ειναι καινουργιο', 'Это новое', 'זה חדש', 'إنه جديد', 'नया है वह', '它是新的'],
'it is first' : ['es ist zuerst', 'c\'est d\'abord', 'es primero', 'è il primo', 'hoc est primum', 'είναι το πρώτο', 'это первое', 'זה הראשון', 'هو الأول', 'यह पहले है', '首先'],
'it is last' : ['es ist zuletzt', 'c\'est le dernier', 'Es el último', 'È l\'ultimo', 'ultimo', 'είναι τελευταίο', 'это последнее', 'זה האחרון', 'إنه الأخير', 'यह अंतिम है', '这是最后'],
'it is long' : ['es ist lang', 'c\'est long', 'es largo', 'è lungo', 'longum est', 'είναι μακρύ', 'это долго', 'זה ארוך', 'انه طويل', 'लंबी होती है', '很长'],
'it is great' : ['Es ist toll', 'c\'est super', 'Eso es genial', 'è grande', 'et est magnus', 'είναι υπέροχο', 'это просто супер', 'זה נהדר', 'انه رائع', 'यह बहुत अच्छा है', '这太棒了'],
'it is little' : ['es ist klein', 'c\'est petit', 'es pequeño', 'È poco', 'parum est', 'είναι λίγο', 'это мало', 'זה קטן', 'فمن القليل', 'यह थोड़ा है', '很少'],
'it is own' : ['es ist eigen', 'il est propre', 'es propio', 'è proprio', 'hoc est', 'είναι δικό του', 'это собственное', 'זה משלו', 'إنه ملك', 'यह अपना है', '它是自己的'],
'it is other' : ['es ist andere', 'c\'est autre', 'Es otro', 'è altro', 'Est alius', 'είναι άλλο', 'это другое', 'זה אחר', 'إنه آخر', 'यह अन्य है', '是其他'],
'it is old' : ['es ist alt', 'c\'est vieux', 'es viejo', 'è vecchio', 'est annorum', 'είναι παλιό', 'Это старое', 'זה זקן', 'انه قديم', 'यह पुराना है', '它老了'],
'it is right' : ['es ist richtig', 'c\'est correct', 'Es correcto', 'è giusto', 'IUS', 'είναι σωστό', 'это правильно', 'זה נכון', 'هذا صحيح', 'यह सही है', '这是正确的'],
'it is big' : ['es ist groß', 'c\'est gros', 'es grande', 'è grande', 'est magnus', 'είναι μεγάλο', 'это большой', 'זה גדול', 'إنه كبير', 'यह बड़ा है', '它很大'],
'it is high' : ['es ist hoch', 'c\'est élevé', 'Es alto', 'è alto', 'est princeps', 'είναι υψηλό', 'это высоко', 'זה גבוה', 'أنها عالية', 'यह उच्च है', '它很高'],
'it is different' : ['es ist anders', 'c\'est différent', 'es diferente', 'è diverso', 'differt', 'είναι διαφορετικό', 'это отличается', 'זה שונה', 'انه مختلف', 'ये अलग है', '它是不同的'],
'it is small' : ['es ist klein', 'c\'est petit', 'es pequeño', 'è piccolo', 'Est parva', 'ειναι μικρο', 'он мал', 'זה קטן', 'إنها صغيرة', 'यह छोटा है', '它很小'],
'it is large' : ['es ist gross', 'c\'est large', 'es largo', 'è grande', 'est magna', 'είναι μεγάλο', 'это большое', 'זה גדול', 'كانت كبيرة', 'यह बड़ा है', '它很大'],
'it is next' : ['es ist als nächstes', 'c\'est à côté', 'es el siguiente', 'è il prossimo', 'hoc est altera', 'ειναι διπλα', 'это следующее', 'זה הבא', 'إنه التالي', 'यह अगला है', '这是下一个'],
'it is early' : ['Es ist früh', 'Il est tôt', 'Es temprano', 'È presto', 'est diluculo', 'είναι νωρίς', 'Это рано', 'מוקדם', 'إن الوقت مبكر', 'बहुत जल्दी है', '现在还早'],
'it is young' : ['Es ist jung', 'c\'est jeune', 'es joven', 'è giovane', 'Est iuvenes', 'είναι νέος', 'Это молодо', 'זה צעיר', 'إنه شاب', 'यह युवा है', '还很年轻'],
'it is important' : ['es ist wichtig', 'c\'est important', 'es importante', 'è importante', 'Aliquam sit amet', 'είναι σημαντικό', 'это важно', 'זה חשוב', 'انه مهم', 'क्या यह महत्वपूर्ण है', '这很重要'],
'it is few' : ['Es ist nur wenige', 'c\'est peu', 'Es pocos', 'è pochi', 'pauci', 'είναι λίγα', 'Это немного', 'זה מעטים', 'إنه قليل', 'यह कुछ है', '很少'],
'it is public' : ['Es ist öffentlich', 'c\'est public', 'es público', 'è pubblico', 'est publicae', 'είναι δημόσιο', 'это публично', 'זה ציבורי', 'إنه عام', 'यह सार्वजनिक है', '它是公开的'],
'it is bad' : ['es ist schlecht', 'c\'est mauvais', 'es malo', 'è cattivo', 'malum', 'Ειναι κακο', 'это плохо', 'זה רע', 'إنه سيء', 'यह बुरा है', '这是坏的'],
'it is same' : ['das ist gleich', 'c\'est pareil', 'es lo mismo', 'è lo stesso', 'idem', 'είναι το ίδιο', 'Это то же самое', 'זה אותו הדבר', 'هذا هو نفسه', 'यह समान है', '是一样的'],
'it is able' : ['es ist in der Lage', 'c\'est capable', 'es capaz', 'è in grado', 'non potest', 'είναι σε θέση', 'это способно', 'זה מסוגל', 'إنه قادر', 'यह सक्षम है', '它能够'],
'it is human' : ['Es ist menschlich', 'c\'est humain', 'es humano', 'è umano', 'est humanum', 'είναι ανθρώπινο', 'Это человек', 'זה אנושי', 'إنه إنسان', 'यह मानव है', '它是人类'],
'it is local' : ['Es ist lokal', 'c\'est local', 'es local', 'è locale', 'est locus', 'είναι τοπικό', 'это местное', 'זה מקומי', 'إنه محلي', 'यह स्थानीय है', '它是本地的'],
'it is general' : ['Es ist allgemein', 'c\'est général', 'es general', 'è generale', 'Est generalis', 'είναι γενικό', 'это общее', 'זה כללי', 'إنه عام', 'यह सामान्य है', '这是一般的'],
'it is full' : ['es ist voll', 'c\'est plein', 'Está lleno', 'è pieno', 'plenum', 'είναι γεμάτο', 'она полна', 'זה מלא', 'انه ممتلىء', 'यह पूर्ण है', '它已经满了'],
'it is possible' : ['es ist möglich', 'c\'est possible', 'es posible', 'è possibile', 'Possibile est', 'είναι δυνατόν', 'это возможно', 'זה אפשרי', 'إنه ممكن', 'यह संभव है', '有可能的'],
'it is major' : ['Es ist wichtig', 'c\'est majeur', 'es mayor', 'è importante', 'est major', 'είναι σημαντικό', 'это главное', 'זה גדול', 'إنه كبير', 'यह प्रमुख है', '这是主要的'],
'it is current' : ['es ist aktuell', 'c\'est le courant', 'es actual', 'è attuale', 'est current', 'είναι τρέχουσα', 'это ток', 'זה עדכני', 'إنه حالي', 'यह वर्तमान है', '它是最新的'],
'it is national' : ['Es ist national', 'c\'est national', 'es nacional', 'è nazionale', 'Est National', 'είναι εθνικό', 'это национальное', 'זה לאומי', 'إنه وطني', 'यह राष्ट्रीय है', '它是民族'],
'it is personal' : ['Es ist persönlich', 'c\'est personnel', 'es personal', 'è personale', 'Est personalis', 'είναι προσωπικό', 'это личное', 'זה אישי', 'إنه شخصي', 'यह व्यक्तिगत है', '这是个人的'],
'it is open' : ['ist geöffnet', 'c\'est ouvert', 'está abierto', 'è aperto', 'Est aperta', 'είναι ανοιχτό', 'Открыто', 'זה פתוח', 'إنه مفتوح', 'यह खुला है', '它是开放的'],
'it is red' : ['es ist rot', 'c\'est rouge', 'es rojo', 'è rosso', 'Est rubrum', 'είναι κόκκινο', 'оно красное', 'זה אדום', 'انه أحمر', 'यह लाल है', '它是红色的'],
'it is difficult' : ['es ist schwierig', 'c\'est difficile', 'es difícil', 'è difficile', 'difficile est', 'είναι δύσκολο', 'это трудно', 'זה קשה', 'إنها صعبة', 'यह मुश्किल है', '这很困难'],
'it is available' : ['es ist verfügbar', 'c\'est disponible', 'está disponible', 'è disponibile', 'praesto est', 'αυτό είναι διαθέσιμο', 'это доступно', 'זה זמין', 'إنه متوفر', 'यह उपलब्ध है', '它可用'],
'it is economic' : ['Es ist wirtschaftlich', 'c\'est économique', 'es económico', 'È economico', 'Est oeconomica', 'είναι οικονομικό', 'это экономическое', 'זה כלכלי', 'إنه اقتصادي', 'यह आर्थिक है', '这是经济的'],
'it is political' : ['Es ist politisch', 'c\'est politique', 'es político', 'è politico', 'est politica', 'είναι πολιτικό', 'это политическое', 'זה פוליטי', 'إنه سياسي', 'यह राजनीतिक है', '这是政治性的'],
'it is sure' : ['es ist sicher', 'c\'est sûr', 'es seguro', 'è certo', 'hoc est certus', 'είναι σίγουρο', 'это уверен', 'זה בטוח', 'انه مؤكد', 'यह सुनिश्चित किया जाता है', '确定'],
'it is clear' : ['alles klar', 'c\'est clair', 'Está despejado', 'è chiaro', 'Clarum est', 'είναι ξεκάθαρο', 'Ясно', 'זה ברור', 'الأمر الواضح', 'यह स्पष्ट है', '很明显'],
'it is white' : ['es ist weiss', 'c\'est blanc', 'Es blanco', 'è bianco', 'album est', 'είναι λευκό', 'Он белый', 'זה לבן', 'انه ابيض', 'यह सफेद है', '它是白色的'],
'it is free' : ['Es ist frei', 'ce est gratuit', 'es gratis', 'è gratis', 'est liberum', 'είναι δωρεάν', 'это бесплатно', 'זה בחינם', 'انه مجانا', 'ये मुफ्त है', '这是免费的'],
'it is short' : ['es ist kurz', 'c\'est court', 'es corta', 'è corto', 'Est brevis', 'είναι σύντομο', 'это короткое', 'זה קצר', 'إنه قصير', 'यह छोटा है', '很短'],
'it is easy' : ['es ist leicht', 'c\'est facile', 'es fácil', 'è facile', 'facile est', 'είναι εύκολο', 'Это просто', 'זה קל', 'إنها سهلة', 'यह आसान है', '这很容易'],
'it is strong' : ['es ist stark', 'c\'est fort', 'es fuerte', 'È forte', 'fortis', 'είναι δυνατό', 'это сильное', 'זה חזק', 'انه قوي', 'यह मजबूत है', '它很强'],
'it is whole' : ['es ist ganz', 'c\'est entier', 'está completo', 'è intero', 'totum', 'είναι ολόκληρο', 'это целое', 'זה שלם', 'إنه كله', 'यह पूरा है', '这是完整的'],
'it is heavy' : ['es ist schwer', 'c\'est lourd', 'Es pesado', 'è pesante', 'Gravis est', 'είναι βαρύ', 'это тяжело', 'זה כבד', 'أنها ثقيلة', 'यह भारी है', '很重'],
'it is happy' : ['es ist glücklich', 'c\'est joyeux', 'es feliz', 'è felice', 'Est felix', 'Είναι χαρούμενο', 'Это счастлива', 'זה שמח', 'هو سعيد', 'यह खुश है', '很高兴'],
'it is true' : ['es stimmt', 'c\'est vrai', 'es verdad', 'è vero', 'ita vero', 'είναι αλήθεια', 'это правда', 'זה נכון', 'هذا صحيح', 'ये सच है', '是真的'],
'it is social' : ['Es ist sozial', 'c\'est social', 'es social', 'è sociale', 'Est Social', 'είναι κοινωνικό', 'это социальное', 'זה חברתי', 'إنه اجتماعي', 'यह सामाजिक है', '这是社交'],
'it is necessary' : ['es ist notwendig', 'il est nécessaire', 'es necesario', 'è necessario', 'necesse est', 'είναι απαραίτητο', 'Это необходимо', 'זה הכרחי', 'انه ضروري', 'यह आवश्यक है', '有必要'],
'it is single' : ['Es ist Single', 'c\'est célibataire', 'es soltero', 'è single', 'est unum', 'είναι ανύπαντρη', 'это холост', 'זה רווק', 'إنه أعزب', 'यह सिंगल है', '它是单身'],
'it is separate' : ['es ist getrennt', 'c\'est séparé', 'está separado', 'è separato', 'separatum', 'είναι ξεχωριστό', 'это отдельно', 'זה נפרד', 'إنه منفصل', 'यह अलग है', '它是独立的'],
'it is wrong' : ['es ist falsch', 'il est faux', 'está mal', 'è sbagliato', 'est nefas', 'είναι λάθος', 'это неверно', 'זה לא נכון', 'انه خطأ', 'गलत बात है', '这是错误的'],
'it is ready' : ['Es ist bereit', 'c\'est prêt', 'esta listo', 'è pronto', 'paratus', 'είναι έτοιμο', 'готово', 'זה מוכן', 'إنه جاهز', 'यह तैयार है', '已经准备好了'],
'it is complex' : ['Es ist komplex', 'c\'est complexe', 'Es complejo', 'è complesso', 'Est complex', 'είναι περίπλοκο', 'это сложно', 'זה מורכב', 'إنه معقد', 'यह जटिल है', '这很复杂'],
'it is tall' : ['es ist groß', 'c\'est grand', 'Es alto', 'è alto', 'est alta', 'είναι ψηλό', 'Это высокий', 'זה גבוה', 'هو طويل القامة', 'यह ऊंचा है', '它很高'],
'it is poor' : ['Es ist arm', 'c\'est pauvre', 'es pobre', 'è scarso', 'Est pauper', 'είναι φτωχό', 'это плохо', 'זה עני', 'إنه فقير', 'यह गरीब है', '它很差'],
'it is global' : ['Es ist global', 'c\'est mondial', 'es global', 'È globale', 'est global', 'είναι παγκόσμιο', 'это глобально', 'זה גלובלי', 'إنه عالمي', 'यह वैश्विक है', '它是全球的'],
'it is environmental' : ['Es ist Umwelt', 'c\'est environnemental', 'es ambiental', 'È ambientale', 'Est environmental', 'είναι περιβαλλοντικό', 'Это экологический', 'זה סביבתי', 'إنه بيئي', 'यह पर्यावरण है', '它是环境的'],
'it is financial' : ['Es ist finanziell', 'c\'est financier', 'es financiero', 'è finanziario', 'Est financial', 'είναι οικονομικό', 'это финансово', 'זה פיננסי', 'إنه مالي', 'यह वित्तीय है', '这是财务'],
'it is blue' : ['es ist blau', 'c\'est bleu', 'es azul', 'è blu', 'caeruleum', 'είναι μπλε', 'оно голубое', 'זה כחול', 'انه ازرق', 'यह नीला है', '它是蓝色的'],
'it is democratic' : ['Es ist demokratisch', 'c\'est démocratique', 'es democrático', 'È democratico', 'est popularis', 'είναι δημοκρατικό', 'Это демократично', 'זה דמוקרטי', 'إنه ديمقراطي', 'यह लोकतांत्रिक है', '它是民主的'],
'it is cool' : ['es ist cool', 'c\'est cool', 'Es genial', 'è fresco', 'frigus est', 'ειναι ΕΝΤΑΞΕΙ', 'это круто', 'זה מגניב', 'إنه بارد', 'यह अच्छा है', '很酷'],
'it is green' : ['es ist grün', 'il est vert', 'es verde', 'è verde', 'est viride', 'είναι πράσινο', 'это зеленое', 'זה ירוק', 'انه اخضر', 'यह हरे रंग का है', '它是绿色的'],
'it is hot' : ['es ist heiß', 'il fait chaud', 'hace calor', 'è caldo', 'iratus est', 'είναι ζεστό', 'горячо', 'זה חם', 'الجو حار', 'गर्मी हो रही है', '很热'],
'it is yellow' : ['es ist gelb', 'c\'est jaune', 'es amarillo', 'è giallo', 'Est flavo', 'είναι κίτρινο', 'Это желтое', 'זה צהוב', 'إنه أصفر', 'यह पीला है', '它是黄色的'],
'it is final' : ['Es ist endgültig', 'c\'est final', 'es final', 'è definitivo', 'Est finalis', 'είναι τελικό', 'это окончательно', 'זה סופי', 'إنه نهائي', 'यह अंतिम है', '这是最终'],
'it is nice' : ['Es ist nett', 'c\'est gentil', 'es agradable', 'è carino', 'hoc est nice', 'είναι ωραίο', 'это мило', 'זה נחמד', 'هذا لطيف', 'यह अच्छा है', '很好'],
'it is sweet' : ['es ist süß', 'c\'est doux', 'Es dulce', 'è dolce', 'Dulce est', 'Είναι γλυκό', 'это мило', 'זה מתוק', 'إنه لطيف', 'यह मीठा है', '很甜'],
'it is sour' : ['Es ist sauer', 'c\'est aigre', 'es agrio', 'è acido', 'acerbi', 'είναι ξινό', 'это кислый', 'זה חמוץ', 'إنه حامض', 'यह खट्टा है', '它是酸的'],
'it is bitter' : ['Es ist bitter', 'c\'est amer', 'es amargado', 'È amaro', 'est amarum', 'είναι πικρό', 'это горько', 'זה מריר', 'إنه مرير', 'यह कड़वा है', '这是痛苦的'],
'it is spicy' : ['Es ist scharf', 'c\'est épicé', 'es picante', 'è piccante', 'Est CONDITUS', 'είναι πικάντικο', 'это острый', 'זה חריף', 'إنه حار', 'यह मसालेदार है', '这很辣'],
'it is salty' : ['Es ist salzig', 'c\'est salé', 'es salado', 'è salato', 'Est salsa', 'είναι αλμυρό', 'это солено', 'זה מלוח', 'إنه مالح', 'यह नमकीन है', '咸'],
'it is fresh' : ['es ist frisch', 'c\'est frais', 'es fresco', 'È fresco', 'Est nova', 'είναι φρέσκο', 'Это свежее', 'זה טרי', 'إنه جديد', 'यह ताजा है', '它是新鲜的'],
'it is dry' : ['es ist trocken', 'c\'est sec', 'Está seco', 'è asciutto', 'siccum est', 'Είναι ξηρό', 'это сухо', 'זה יבש', 'فهو جاف', 'यह सूखा है', '它是干的'],
'it is moist' : ['Es ist feucht', 'il est humide', 'es húmedo', 'È umido', 'est humidum', 'είναι υγρό', 'это влажное', 'זה לח', 'إنه رطب', 'यह नम है', '这是潮湿的'],
'it is soft' : ['es ist weich', 'c\'est doux', 'es suave', 'è morbido', 'est mollis', 'είναι μαλακό', 'это мягкое', 'זה רך', 'انها ناعمة', 'यह नरम है', '它柔软'],
'it is hard' : ['es ist schwer', 'c\'est difficile', 'es difícil', 'è difficile', 'durum est', 'είναι δύσκολο', 'это трудно', 'זה קשה', 'انه صعب', 'वह कठिन है', '很难'],
'it is solid' : ['Es ist solide', 'c\'est solide', 'es sólido', 'è solido', 'Est solidum', 'είναι σταθερό', 'это твердое', 'זה מוצק', 'إنه صلب', 'यह ठोस है', '它是坚固的'],
'it is liquid' : ['Es ist flüssig', 'c\'est liquide', 'es líquido', 'è liquido', 'liquidum est', 'είναι υγρό', 'это жидкость', 'זה נוזלי', 'إنه سائل', 'यह तरल है', '它是液体'],
'it is fuzzy' : ['Es ist unscharf', 'c\'est flou', 'es difuso', 'È confuso', 'Est Fuzzy', 'είναι ασαφές', 'это нечетко', 'זה מטושטש', 'إنه غامض', 'यह फजी है', '这是模糊的'],
'it is slimy' : ['Es ist schleimig', 'c\'est visqueux', 'es viscoso', 'È viscido', 'est radix', 'είναι γλοιώδες', 'это слизи', 'זה רזה', 'إنه غليظ', 'यह पतला है', '这很粘'],
'it is smooth' : ['es ist glatt', 'c\'est lisse', 'es suave', 'è liscio', 'Est lenis', 'είναι ομαλό', 'это гладко', 'זה חלק', 'إنه سلس', 'यह चिकना है', '它很顺利'],
'it is rough' : ['es ist rau', 'c\'est rugueux', 'Es duro', 'è ruvido', 'Est aspera', 'είναι τραχύ', 'это грубо', 'זה מחוספס', 'إنه خشن', 'यह खुरदरा है', '这很粗糙'],
'it is sharp' : ['es ist scharf', 'c\'est tranchant', 'es agudo', 'è acuto', 'Est acri', 'είναι αιχμηρό', 'это резкое', 'זה חד', 'إنه حاد', 'यह तेज है', '它很锋利'],
'it is dull' : ['Es ist langweilig', 'c\'est terne', 'es aburrido', 'è noioso', 'Est hebes', 'είναι θαμπό', 'это скучно', 'זה משעמם', 'إنه ممل', 'यह सुस्त है', '很乏味'],
'it is round' : ['Es ist rund', 'c\'est rond', 'es redondo', 'é rotondo', 'est per', 'είναι στρογγυλό', 'Это круглый', 'זה עגול', 'إنه مستدير', 'वो गोल है', '它是圆形的'],
'it is square' : ['Es ist quadratisch', 'c\'est carré', 'Es cuadrado', 'è quadrato', 'est quadratum', 'είναι τετράγωνο', 'это квадратный', 'זה מרובע', 'إنه مربع', 'यह वर्ग है', '它是正方形'],
'it is rectangular' : ['Es ist rechteckig', 'c\'est rectangulaire', 'es rectangular', 'è rettangolare', 'Est rectangulum', 'είναι ορθογώνιο', 'Это прямоугольный', 'זה מלבני', 'إنه مستطيل', 'यह आयताकार है', '它是矩形'],
'it is triangular' : ['Es ist dreieckig', 'c\'est triangulaire', 'es triangular', 'è triangolare', 'Est triangular', 'είναι τριγωνικό', 'Это треугольный', 'זה משולש', 'إنه الثلاثي', 'यह त्रिकोणीय है', '它是三角形的'],
'it is cylindrical' : ['Es ist zylindrisch', 'c\'est cylindrique', 'es cilíndrico', 'È cilindrico', 'Est cylindricus', 'είναι κυλινδρικό', 'это цилиндрическое', 'זה גלילי', 'إنه أسطواني', 'यह बेलनाकार है', '它是圆柱形的'],
'it is conical' : ['Es ist konisch', 'c\'est conique', 'es cónico', 'è conico', 'Est Conical', 'είναι κωνικό', 'это коническое', 'זה חרוטי', 'إنه مخروطي', 'यह शंक्वाकार है', '它是圆锥形的'],
'it is irregular' : ['Es ist unregelmäßig', 'c\'est irrégulier', 'es irregular', 'è irregolare', 'Est irregularis', 'είναι ακανόνιστο', 'это нерегулярно', 'זה לא סדיר', 'إنه غير منتظم', 'यह अनियमित है', '它是不规则的'],
'it is straight' : ['es ist gerade', 'c\'est droit', 'es recto', 'è dritto', 'rectum est', 'είναι ευθεία', 'это прямо', 'זה ישר', 'إنه مستقيم', 'यह सीधा है', '这是笔直的'],
'it is curved' : ['es ist gebogen', 'Il est incurvé', 'es curvado', 'è curvo', 'curvam', 'Είναι καμπύλο', 'это изогнуто', 'זה מעוקל', 'إنه منحني', 'यह घुमावदार है', '它是弯曲的'],
'it is thin' : ['es ist dünn', 'il est mince', 'es delgado', 'è sottile', 'factum est tenuis', 'είναι λεπτό', 'это тонко', 'זה רזה', 'إنه نحيف', 'यह पतला है', '它很薄'],
'it is thick' : ['es ist dick', 'c\'est épais', 'es grueso', 'è denso', 'est densissima', 'είναι παχύ', 'это густо', 'זה עבה', 'إنه سميك', 'यह मोटी है', '它很厚']
}

# %% dict dicts
dict_dicts = {
'V': dict_verbs,
'N': dict_nouns,
'A': dict_adjs      
}